server:
  port: 9020
  forward-headers-strategy: native
  max-http-header-size: 16KB

spring:
  application:
    name: hyperativa-be
  servlet:
    multipart:
      max-request-size: 5MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/hyperativadb-dev}
    username: ${DB_USERNAME:devuser}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: hikari-cp
      connection-timeout: 60000
      minimum-idle: ${IDLE_CONNECTION:3}
      maximum-pool-size: 100
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      dll-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        default_schema: public
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: public

  management:
    endpoint:
      metrics:
        enabled: true
    web:
      exposure:
        include:  metrics

application:
  security:
    issuer: ${JWT_ISSUER:hyperativa-api}
    token-settings:
      access:
        secret: ${ACCESS_JWT_SECRET:my-secret-key}
        ttl: ${ACCESS_JWT_TTL:3600}
  card:
    cryptoSecret: ${CARD_CRYPTO_SECRET:2Zp6qULfy4eYXTN3pKmvzmp6X8MGjVVo}
    hashSecret: ${CARD_HASH_SECRET:any-test-secret-key-123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.gijoefan: INFO